### ISSUE TITLE
Deploy all features to fossasia.net github site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/api.fossasia.net#52]
* [ ] Implement FOSSASIA.net map as native map (compare fossasia.github.io)  https://github.com/fossasia/fossasia.net/issues/1
* [ ] Implement FOSSASIA.net community list as in fossasia.github.io  https://github.com/fossasia/fossasia.net/issues/3 
* [ ] Implement FOSSASIA.net community calendar based on data from API  https://github.com/fossasia/fossasia.net/issues/2
* [ ] Add info about set up, architecture and dependencies to Readme.md https://github.com/fossasia/fossasia.net/issues/4
